mqtt:
  server: tcp://127.0.0.1:1883
  fbserver: tcp://0.0.0.0:1885
  username: ""
  password: ""
  certification: ""
dingTalk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=e79d127635b34ce6992539a2a2794978136947f4e7f33eaccc5394828d72f570
configmap: /opt/kubeedge/deviceProfile.json

